{
 "title": "Nordea Kong (official)",
 "description": "Dashboard that graphs metrics exported via Prometheus plugin in Kong (http://github.com/kong/kong)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kong_http_requests_total,namespace)"
    }
   },
   {
    "name": "service",
    "query": "label_values(kong_http_requests_total,service)"
   },
   {
    "name": "instance",
    "query": "label_values(kong_nginx_connections_total,instance)"
   },
   {
    "name": "route",
    "query": "label_values(kong_http_requests_total,route)"
   },
   {
    "name": "upstream",
    "query": "label_values(kong_upstream_target_health, upstream)"
   },
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "range",
    "query": "2m,3m,5m,10m,15m,30m,1h,2h,4h,6h,12h,1d,4d,7d,14d,30d, 1m, 90s"
   },
   {
    "name": "code",
    "query": {
     "query": "label_values(kong_http_requests_total,code)"
    }
   },
   {
    "name": "consumer",
    "query": {
     "query": "label_values(kong_http_requests_total,consumer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request rate - no cousumer filtering",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total requests per second (RPS) per host - stacked",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{instance=~\"$instance\", namespace=~\"$namespace\"}[$range])) by (host)",
     "legendFormat": "{{host}} Requests/second"
    }
   ]
  },
  {
   "title": "Total requests per second (RPS) per consumer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{instance=~\"$instance\", consumer=~\"$consumer\", namespace=~\"$namespace\"}[$range])) by (consumer)",
     "legendFormat": "{{consumer}}"
    }
   ]
  },
  {
   "title": "RPS per service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", instance=~\"$instance\", namespace=~\"$namespace\"}[$range])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "RPS per route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", instance=~\"$instance\", namespace=~\"$namespace\"}[$range])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  { "title": "Request rate per status code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "RPS per status code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", code =~\"$code\", instance=~\"$instance\", namespace=~\"$namespace\"}[$range])) by  (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "RPS per service and code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", code =~\"$code\", instance=~\"$instance\", namespace=~\"$namespace\"}[$range])) by (service, code)",
     "legendFormat": "{{service}} {{code}}"
    }
   ]
  },
  {
   "title": "RPS per route and code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", code =~\"$code\", instance=~\"$instance\", namespace=~\"$namespace\"}[$range])) by (route, code)",
     "legendFormat": "{{route}} {{code}}"
    }
   ]
  },
  { "title": "RPS success and error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "RPS per route and code - success 2xx and 3xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", code =~\"$code\", code =~\"2..|3..\", instance=~\"$instance\", namespace=~\"$namespace\"}[$range])) by (route, code)",
     "legendFormat": "{{route}} {{code}}"
    }
   ]
  },
  {
   "title": "RPS per route and code - error 4xx and 5xx - from upstream service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\", code =~\"$code\", code =~\"4..|5..\", instance=~\"$instance\", namespace=~\"$namespace\", source=\"service\"}[$range])) by (route, code, source)",
     "legendFormat": "{{route}} {{code}} {{source}}"
    }
   ]
  },
  {
   "title": "RPS per route and code - error 4xx and 5xx - from upstream kong",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{service=~\"$service\", route=~\"$route\",  code =~\"$code\", code =~\"4..|5..\", instance=~\"$instance\", namespace=~\"$namespace\", source!=\"service\"}[$range])) by (route, code, source)",
     "legendFormat": "{{route}} {{code}} {{source}}"
    }
   ]
  },
  { "title": "RPS per consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Total requests per second (RPS) per consumer per code from Upstream service - SUCCESS 2xx and 3xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{instance=~\"$instance\", consumer=~\"$consumer\",code =~\"$code\",  namespace=~\"$namespace\", code =~\"2..|3..\", source=\"service\"}[$range])) by (consumer, source, code)",
     "legendFormat": "{{consumer}} {{code}} {{source}}"
    }
   ]
  },
  {
   "title": "Total requests per second (RPS) per consumer per code from Upstream service - ERROR 4xx and 5xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{instance=~\"$instance\", consumer=~\"$consumer\",code =~\"$code\",  namespace=~\"$namespace\", code =~\"4..|5..\", source=\"service\"}[$range])) by (consumer, source, code)",
     "legendFormat": "{{consumer}} {{code}} {{source}}"
    }
   ]
  },
  {
   "title": "Total requests per second (RPS) per consumer/route per code from Upstream service - SUCCESS 2xx and 3xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{instance=~\"$instance\", consumer=~\"$consumer\",code =~\"$code\", code =~\"2..|3..\", namespace=~\"$namespace\", source=\"service\"}[$range])) by (consumer, route, source, code)",
     "legendFormat": "{{consumer}} {{route}} {{code}} {{source}}"
    }
   ]
  },
  {
   "title": "Total requests per second (RPS) per consumer/route per code from Upstream service - ERROR 4xx and 5xx",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{instance=~\"$instance\", consumer=~\"$consumer\",code =~\"$code\", code =~\"4..|5..\", namespace=~\"$namespace\", source=\"service\"}[$range])) by (consumer, route, source, code)",
     "legendFormat": "{{consumer}} {{route}} {{code}} {{source}}"
    }
   ]
  },
  {
   "title": "Total requests per second (RPS) per consumer per code from Kong",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{instance=~\"$instance\", consumer=~\"$consumer\",code =~\"$code\",  namespace=~\"$namespace\", source!=\"service\"}[$range])) by (consumer, source, code)",
     "legendFormat": "{{consumer}} {{code}} {{source}}"
    }
   ]
  },
  {
   "title": "Total requests per second (RPS) per consumer/route/code per code from Kong",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total{instance=~\"$instance\", route=~\"$route\", consumer=~\"$consumer\",code =~\"$code\",  namespace=~\"$namespace\", source!=\"service\"}[$range])) by (consumer, route, source, code)",
     "legendFormat": "{{consumer}} {{route}} {{code}} {{source}}"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kong Proxy Latency across all services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{instance=~\"$instance\"}[$range])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{instance=~\"$instance\"}[$range])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{instance=~\"$instance\"}[$range])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Kong Proxy Latency per Service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{ service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (service,le))",
     "legendFormat": "p90-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{ service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (service,le))",
     "legendFormat": "p95-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{ service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (service,le))",
     "legendFormat": "p99-{{service}}"
    }
   ]
  },
  {
   "title": "Kong Proxy Latency per Route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_kong_latency_ms_bucket{ service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (route,le))",
     "legendFormat": "p90-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_kong_latency_ms_bucket{ service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (route,le))",
     "legendFormat": "p95-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_kong_latency_ms_bucket{ service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (route,le))",
     "legendFormat": "p99-{{route}}"
    }
   ]
  },
  {
   "title": "Request Time across all services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{}[$range])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{}[$range])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{}[$range])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Request Time per service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (service,le))",
     "legendFormat": "p90-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (service,le))",
     "legendFormat": "p95-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (service,le))",
     "legendFormat": "p99-{{service}}"
    }
   ]
  },
  {
   "title": "Request Time per Route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (route,le))",
     "legendFormat": "p90-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (route,le))",
     "legendFormat": "p95-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_request_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (route,le))",
     "legendFormat": "p99-{{route}}"
    }
   ]
  },
  {
   "title": "Upstream time across all services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{}[$range])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{}[$range])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{}[$range])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Upstream Time across per service",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (service,le))",
     "legendFormat": "p90-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (service,le))",
     "legendFormat": "p95-{{service}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (service,le))",
     "legendFormat": "p99-{{service}}"
    }
   ]
  },
  {
   "title": "Upstream Time across per Route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (route,le))",
     "legendFormat": "p90-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (route,le))",
     "legendFormat": "p95-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_upstream_latency_ms_bucket{service =~ \"$service\",route=~\"$route\",instance=~\"$instance\"}[$range])) by (route,le))",
     "legendFormat": "p99-{{route}}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{instance=~\"$instance\", namespace=~\"$namespace\"}[$range])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Egress per service/route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{direction=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\", namespace=~\"$namespace\"}[$range])) by (service)",
     "legendFormat": "service:{{service}}"
    },
    {
     "expr": "sum(irate(kong_bandwidth_bytes{direction=\"egress\", service =~\"$service\",route=~\"$route\",instance=~\"$instance\", namespace=~\"$namespace\"}[$range])) by (route)",
     "legendFormat": "route:{{route}}"
    }
   ]
  },
  {
   "title": "Ingress per service/route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_bandwidth_bytes{direction=\"ingress\", service =~\"$service\", namespace=~\"$namespace\"}[$range])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Caching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kong shared memory usage by Node ($instance)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 154 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kong_memory_lua_shared_dict_bytes{instance=~\"$instance\",shared_dict!~\"kong_process_events\", namespace=~\"$namespace\"}/kong_memory_lua_shared_dict_total_bytes{instance=~\"$instance\",shared_dict!~\"kong_process_events\", namespace=~\"$namespace\"})*100",
     "legendFormat": "{{shared_dict}} ({{kong_subsystem}})"
    }
   ]
  },
  {
   "title": "Kong worker Lua VM usage by Node ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 166 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kong_memory_workers_lua_vms_bytes{instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "PID:{{pid}} ({{kong_subsystem}})"
    }
   ]
  },
  {
   "title": "Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 178 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Healthy status",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
   "targets": [
    {
     "expr": "sum(kong_upstream_target_health{state=\"healthy\",upstream=~\"$upstream\", namespace=~\"$namespace\"}) by (upstream,target,address) * -1  + sum(kong_upstream_target_health{state=~\"(unhealthy|dns_error)\",upstream=~\"$upstream\", namespace=~\"$namespace\"}) by (upstream,target,address)",
     "legendFormat": "{{upstream}}:{{target}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
   "targets": [
    {
     "expr": "sum(\n# map state to a numeric value\n# since grafana doesn't support value mapping yet\n  label_replace(\n    label_replace(\n      label_replace(\n       kong_upstream_target_health{upstream=~\"$upstream\"}\n       # healthy is positive number\n       , \"state_value\", \"1\", \"state\", \"healthy\"\n       # healthchecks_off is 0\n      ), \"state_value\", \"0\", \"state\", \"healthchecks_off\"\n      # unhealthy is negative number\n    ), \"state_value\", \"-1\", \"state\", \"(dns_error|unhealthy)\"\n  )\n)\nby (upstream, target, address, state, state_value) > 0"
    }
   ]
  },
  {
   "title": "Nginx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 187 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Nginx connection state",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=~\"active|reading|writing|waiting\", instance=~\"$instance\", namespace=~\"$namespace\"}) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=\"total\", instance=~\"$instance\", namespace=~\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Handled Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=\"handled\", instance=~\"$instance\", namespace=~\"$namespace\"})",
     "legendFormat": "Handled"
    }
   ]
  },
  {
   "title": "Accepted Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kong_nginx_connections_total{state=\"accepted\", instance=~\"$instance\", namespace=~\"$namespace\"})",
     "legendFormat": "Accepted"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 202 } },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{ instance=~\"$instance\", namespace=~\"$namespace\"}[$range])) by (host)",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "container rss and working set and usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{ instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "memory RSS {{host}}"
    },
    {
     "expr": "container_memory_working_set_bytes{ instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "memory working set {{host}}"
    },
    {
     "expr": "container_memory_usage_bytes{ instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "memory usage {{host}}"
    }
   ]
  },
  {
   "title": "container uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 210 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "{{host}} start time"
    }
   ]
  },
  {
   "title": "container memory cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 210 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_cache{ instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "memory cache {{host}}"
    }
   ]
  },
  {
   "title": "container_memory mapped file",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_mapped_file{ instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "memory mapped file{{host}}"
    }
   ]
  },
  {
   "title": "containercontainer_memory_swap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_swap{ instance=~\"$instance\", namespace=~\"$namespace\"}",
     "legendFormat": "memory swap {{host}}"
    }
   ]
  },
  {
   "title": "container_fs_writes_bytes per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{ instance=~\"$instance\", namespace=~\"$namespace\"}[$range])) by (host)",
     "legendFormat": "CPU usage"
    }
   ]
  }
 ]
}